version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: engine-name-app
    volumes:
      - ./:/var/www
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    container_name: engine-name-nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true
